language: node_js
node_js:
  - 12
install:
  - npm install -g zcatalyst-cli
jobs:
  include:
    - stage: functions
      before_script:
        - cd functions/catly
        - pwd
      script:
        - echo 'functions!!'
        - echo 'Installing Dependencies!'
        - npm install
      after_success:
        - echo 'deploying functions!'
        - catalyst deploy --only functions --project <project-id> --verbose --token <cli-token>
    - stage: client
      before_script:
        - cd client/app
        - pwd
      script:
        - echo 'client!!'
        - echo 'Installing Dependencies!'
        - yarn install
        - yarn build
        - cp ../client-package.json build/.
        - cd build
      after_success:
        - echo 'deploying client!'
        - catalyst deploy --only client --project <project-id> --verbose --token <cli-token>